# Generated by Django 3.1.4 on 2020-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender',
            name='name',
            field=models.CharField(help_text='Vender Name', max_length=80, null=True),
        ),
    ]
